serve:       true
lsi:         true
highligher:  rouge
markdow:     kramdown
permalink:   date
feed:
  path: /feed.atom
exclude:
  - README.md
  - config.rb
plugins:
  - jekyll-sitemap
  - jekyll-feed
